# -- Main Menu --
# The main menu is displayed in the header at the top of the page.

[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "Research"
  pageRef = "research"
  weight = 30

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 40
